package pkg1;


import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.rmi.RemoteException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import model.User;
import rmi.client.ClientListener;
import view.ClientInputHandler;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Radwa Manssour
 */
public class chatCui extends javax.swing.JFrame {

    /**
     * Creates new form chatCui
     */
    String userMail;
    public User user;
    //public ClientListener clientListener;
    ClientInputHandler cih;
    public void setUser(User user) {
        this.user = user;
    }

/*    public ClientListener getClientListener() {
        return clientListener;
    }*/
    
    public void setUserMail(String mail){
        userMail=mail;
    }
    public  JPanel parentPanel;
    public  messenger mess;
    public  rooms room;
    public chatCui(ClientInputHandler cih) {
        initComponents();
        this.cih=cih;
        room=new rooms();
        setSize(300, 700);
        room.setVisible(false);
        signInPanel signIn=new signInPanel(this,cih);
        signUpPanel signUp=new signUpPanel(this,cih);
        parentPanel=new JPanel();
        parentPanel.setLayout(new CardLayout());
        parentPanel.add("signin", signIn);
        parentPanel.add("signup", signUp);
        p.add(parentPanel,BorderLayout.WEST);
        p.add(room,BorderLayout.CENTER);
        conversation conv=new conversation();
        room.rooms_tabs.insertTab("", new ImageIcon(""), conv,"",0);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        p = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 0));
        setResizable(false);

        p.setBackground(new java.awt.Color(153, 204, 255));
        p.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new chatCui(new ClientInputHandler()).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    public static javax.swing.JPanel p;
    // End of variables declaration//GEN-END:variables
}
