package pkg1;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import model.Contact;
import model.Message;
import model.Room;
import model.User;
import view.ClientInputHandler;
import view.IClientInputHandler;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Radwa Manssour
 */
public class conversation extends javax.swing.JPanel {

    /**
     * Creates new form conversation
     */
    private String roomId;
    private  Room room;
    private User user;

    public void setRoom(Room room) {
        this.room = room;
    }

    public Room getRoom() {
        return room;
    }

    
    
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    public String getRoomId() {
        return roomId;
    }
    
    public conversation(chatCui gui) {
        initComponents();
        this.user=gui.user;
        setSize(700, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text2 = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        attach = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        attach2 = new javax.swing.JButton();
        attach3 = new javax.swing.JButton();
        attach4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        text1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(450, 0));
        setPreferredSize(new java.awt.Dimension(450, 426));

        img.setText("jLabel1");

        name.setText("name");

        text2.setColumns(20);
        text2.setRows(5);
        jScrollPane1.setViewportView(text2);

        send.setText("send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanel1.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        attach.setMaximumSize(new java.awt.Dimension(35, 35));
        attach.setMinimumSize(new java.awt.Dimension(0, 35));
        attach.setPreferredSize(new java.awt.Dimension(35, 35));
        attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachActionPerformed(evt);
            }
        });
        jPanel1.add(attach);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);

        attach2.setMaximumSize(new java.awt.Dimension(35, 35));
        attach2.setMinimumSize(new java.awt.Dimension(0, 0));
        attach2.setPreferredSize(new java.awt.Dimension(35, 35));
        jPanel1.add(attach2);

        attach3.setText("add member");
        attach3.setMaximumSize(new java.awt.Dimension(100, 35));
        attach3.setMinimumSize(new java.awt.Dimension(0, 0));
        attach3.setPreferredSize(new java.awt.Dimension(100, 35));
        attach3.setRolloverEnabled(false);
        jPanel1.add(attach3);

        attach4.setText("leave conversation");
        attach4.setMaximumSize(new java.awt.Dimension(130, 35));
        attach4.setMinimumSize(new java.awt.Dimension(0, 0));
        attach4.setPreferredSize(new java.awt.Dimension(130, 35));
        jPanel1.add(attach4);

        text1.setColumns(20);
        text1.setRows(5);
        jScrollPane2.setViewportView(text1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(name))
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        String s=text1.getText();
         
        Message m=new Message(roomId, null,user.getUserName(), s, true);
        IClientInputHandler cih=new ClientInputHandler();
        cih.sendMessage(room, m);
    }//GEN-LAST:event_sendActionPerformed

    private void attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachActionPerformed
         JFileChooser f = new JFileChooser();
        if (f.showOpenDialog(conversation.this) == JFileChooser.APPROVE_OPTION) {
            String path = f.getSelectedFile().getPath();
            try {
                FileInputStream fis=new FileInputStream(path);
                int size=fis.available();
                byte[] b=new byte[size];
                fis.read(b);
               // Message m=new Message(roomId, null, null, null, true);
                IClientInputHandler cih=new ClientInputHandler();
                cih.sendFile(b);
               // jTextArea1.setText(new String(b));
                fis.close();
                
            } catch (FileNotFoundException e) {
                System.out.println("FileNotFound");
            } catch (IOException ex) {
                 Logger.getLogger(conversation.class.getName()).log(Level.SEVERE, null, ex);
             }
            
        }
    }//GEN-LAST:event_attachActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attach;
    private javax.swing.JButton attach2;
    private javax.swing.JButton attach3;
    private javax.swing.JButton attach4;
    private javax.swing.JLabel img;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel name;
    private javax.swing.JButton send;
    public static javax.swing.JTextArea text1;
    public static javax.swing.JTextArea text2;
    // End of variables declaration//GEN-END:variables
}
