/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.UUID;
import static javax.swing.JComponent.TOOL_TIP_TEXT_KEY;
import model.Contact;
import model.Message;
import model.Room;

/**
 *
 * @author bishoy
 */
public class GroupContactPannel extends ContactPanel {

    /**
     * Creates new form GroupContactPannel
     * 
     * 
     */
    public GroupContactPannel(chatCui gui,conversation superConv, Contact cont) {
        super(gui, cont);
        initComponents();
        GroupContactPannel c = this;
        addMouseListener(new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent e) {

                c.setBackground(new Color(204, 255, 204));
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    Room room = new Room();
                    room.contactVector = superConv.getRoom().contactVector;
                    //room.contactVector.add(new Contact(gui.user.getUserEmail(), TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY, null, WIDTH));
                    room.contactVector.add(cont);
                    room.setRoomId(UUID.randomUUID().toString());
                    
                    //boolean found = false;
                    /*for (int i = 0; i < gui.room.rooms_tabs.getTabCount(); i++) {
                        if (((conversation) gui.room.rooms_tabs.getComponent(i)).getRoomId().equals(room.getRoomId())) {
                            found = true;
                            break;
                        }
                    }*/
                    if(!gui.rooms.containsKey(room.getRoomId())){
                        conversation conv = new conversation(gui);
                        conv.setRoomId(room.getRoomId());
                        conv.setRoom(room);
                        gui.rooms.put(room.getRoomId(), conv);
                        conv.setVisible(true);
                    }
                    gui.cih.sendMessage(room, new Message(room.getRoomId(), null, "server Message", cont.getName() + " has join the chat group", true));
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                System.out.println("dddhh");
                c.setBackground(new Color(255, 255, 255));
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
