/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkg1;

import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import model.User;
import view.ClientInputHandler;

/**
 *
 * @author Radwa Manssour
 */
public class signUpPanel extends javax.swing.JPanel {

    /**
     * Creates new form signUpPanel
     */
    chatCui gui;
    private ClientInputHandler cih;
    private User u;

    public signUpPanel(chatCui gui, ClientInputHandler cih) {
        initComponents();
        ImageIcon i = new ImageIcon("src\\pkg1\\skype.png");
        jLabel1.setIcon(i);
        this.gui = gui;
        try {
            //HiFiLookAndFeel laf=new HiFiLookAndFeel();
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            System.out.println("Undefined WindowLookAndFeel");
        }
        this.cih = cih;

        u = new User();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fn_txt = new javax.swing.JTextField();
        ln_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        remail_txt = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel1.setBackground(new java.awt.Color(21, 160, 250));
        jLabel1.setText("jLabel1");

        jPasswordField1.setBackground(new java.awt.Color(191, 225, 252));
        jPasswordField1.setForeground(new java.awt.Color(0, 170, 240));
        jPasswordField1.setText("password");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(21, 91, 141));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Up");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gender");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        fn_txt.setBackground(new java.awt.Color(191, 225, 252));
        fn_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fn_txt.setForeground(new java.awt.Color(0, 170, 240));
        fn_txt.setText("frist name");
        fn_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fn_txtFocusLost(evt);
            }
        });
        fn_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fn_txtMouseClicked(evt);
            }
        });

        ln_txt.setBackground(new java.awt.Color(191, 225, 252));
        ln_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ln_txt.setForeground(new java.awt.Color(0, 170, 240));
        ln_txt.setText("last name");
        ln_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ln_txtFocusLost(evt);
            }
        });
        ln_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ln_txtMouseClicked(evt);
            }
        });

        email_txt.setBackground(new java.awt.Color(191, 225, 252));
        email_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        email_txt.setForeground(new java.awt.Color(0, 170, 240));
        email_txt.setText("E-mail");
        email_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_txtFocusLost(evt);
            }
        });
        email_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                email_txtMouseClicked(evt);
            }
        });

        remail_txt.setBackground(new java.awt.Color(191, 225, 252));
        remail_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        remail_txt.setForeground(new java.awt.Color(0, 170, 240));
        remail_txt.setText("confirm email");
        remail_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                remail_txtFocusLost(evt);
            }
        });
        remail_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remail_txtMouseClicked(evt);
            }
        });

        jPasswordField2.setBackground(new java.awt.Color(191, 225, 252));
        jPasswordField2.setForeground(new java.awt.Color(0, 170, 240));
        jPasswordField2.setText("password");
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cancel ?!");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBox1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male" }));
        jComboBox1.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(ln_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(email_txt)
                            .addComponent(jPasswordField1)
                            .addComponent(remail_txt)
                            .addComponent(jPasswordField2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fn_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(ln_txt))
                .addGap(18, 18, 18)
                .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(remail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        String str = jPasswordField1.getText();
        if (str.equals("")) {
            jPasswordField1.setText("password");
            jPasswordField1.setForeground(java.awt.Color.getHSBColor(0, 170, 240));
        } else {
            jPasswordField1.setText(str);
            jPasswordField1.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        String str = jPasswordField1.getText();
        if (str.equals("password")) {
            jPasswordField1.setText("");
            jPasswordField1.setForeground(java.awt.Color.gray);
            //[25,173,250]
        } else {
            jPasswordField1.setText(str);
            jPasswordField1.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void fn_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fn_txtFocusLost
        String str = fn_txt.getText();
        if (str.equals("")) {
            fn_txt.setText("frist name");
            fn_txt.setForeground(java.awt.Color.getHSBColor(0, 170, 240));
        } else {
            fn_txt.setText(str);
            // fn_txt.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_fn_txtFocusLost

    private void fn_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fn_txtMouseClicked
        String str = fn_txt.getText();
        if (str.equals("frist name")) {
            fn_txt.setText("");
            fn_txt.setForeground(java.awt.Color.gray);
        } else {
            fn_txt.setText(str);
            fn_txt.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_fn_txtMouseClicked

    private void ln_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ln_txtFocusLost
        String str = ln_txt.getText();
        if (str.equals("")) {
            ln_txt.setText("last name");
            ln_txt.setForeground(java.awt.Color.getHSBColor(0, 170, 240));
        } else {
            ln_txt.setText(str);
            ln_txt.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_ln_txtFocusLost

    private void ln_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ln_txtMouseClicked
        String str = ln_txt.getText();
        if (str.equals("last name")) {
            ln_txt.setText("");
            ln_txt.setForeground(java.awt.Color.gray);
        } else {
            ln_txt.setText(str);
            ln_txt.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_ln_txtMouseClicked

    private void email_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_txtFocusLost
        String str = email_txt.getText();
        if (str.equals("")) {
            email_txt.setText("E-mail");
            email_txt.setForeground(java.awt.Color.getHSBColor(0, 170, 240));
        } else {
            email_txt.setText(str);
            email_txt.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_email_txtFocusLost

    private void email_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_txtMouseClicked
        String str = email_txt.getText();
        if (str.equals("E-mail")) {
            email_txt.setText("");
            email_txt.setForeground(java.awt.Color.gray);
        } else {
            email_txt.setText(str);
            email_txt.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_email_txtMouseClicked

    private void remail_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remail_txtFocusLost
        String str = remail_txt.getText();
        if (str.equals("")) {
            remail_txt.setText("confirm email");
            remail_txt.setForeground(java.awt.Color.getHSBColor(0, 170, 240));
        } else {
            remail_txt.setText(str);
            remail_txt.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_remail_txtFocusLost

    private void remail_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remail_txtMouseClicked
        String str = remail_txt.getText();
        if (str.equals("confirm email")) {
            remail_txt.setText("");
            remail_txt.setForeground(java.awt.Color.gray);
        } else {
            remail_txt.setText(str);
            remail_txt.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_remail_txtMouseClicked

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        String str = jPasswordField2.getText();
        if (str.equals("")) {
            jPasswordField2.setText("password");
            jPasswordField2.setForeground(java.awt.Color.getHSBColor(0, 170, 240));
        } else {
            jPasswordField2.setText(str);
            jPasswordField2.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        String str = jPasswordField2.getText();
        if (str.equals("password")) {
            jPasswordField2.setText("");
            jPasswordField2.setForeground(java.awt.Color.gray);
            //[25,173,250]
        } else {
            jPasswordField2.setText(str);
            jPasswordField2.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_jPasswordField2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField fn_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField ln_txt;
    private javax.swing.JTextField remail_txt;
    // End of variables declaration//GEN-END:variables
}
